export const Provincias = [
  {
    id: 1,
    nombre: 'Distrito Nacional',
    municipios: ['Distrito Nacional'],
  },
  {
    id: 2,
    nombre: 'Azua',
    municipios: [
      'Azua de Compostela',
      'Estebanía',
      'Guayabal',
      'Las Charcas',
      'Las Yayas de Viajama',
      'Padre Las Casas',
      'Peralta',
      'Pueblo Viejo',
      'Sabana Yegua',
      'Tábara Arriba',
    ],
  },
  {
    id: 3,
    nombre: 'Baoruco',
    municipios: ['Neiba', 'Galván', 'Los Ríos', 'Tamayo', 'Villa Jaragua'],
  },
  {
    id: 4,
    nombre: 'Barahona',
    municipios: [
      'Barahona',
      'Cabral',
      'El Peñón',
      'Enriquillo',
      'Fundación',
      'Jaquimeyes',
      'La Ciénaga',
      'Las Salinas',
      'Paraíso',
      'Polo',
      'Vicente Noble',
    ],
  },
  {
    id: 5,
    nombre: 'Dajabón',
    municipios: [
      'Dajabón',
      'El Pino',
      'Loma de Cabrera',
      'Partido',
      'Restauración',
    ],
  },
  {
    id: 6,
    nombre: 'Duarte',
    municipios: [
      'San Francisco de Macorís',
      'Arenoso',
      'Castillo',
      'Eugenio María de Hostos',
      'Las Guáranas',
      'Pimentel',
      'Villa Riva ',
    ],
  },
  {
    id: 7,
    nombre: 'El Seibo',
    municipios: ['El Seibo', 'Miches'],
  },
  {
    id: 8,
    nombre: 'Elías Piña',
    municipios: [
      'Comendador',
      'Bánica',
      'El Llano',
      'Hondo Valle',
      'Las Guáranas',
      'Juan Santiago',
      'Pedro Santana',
    ],
  },
  {
    id: 9,
    nombre: 'Espaillat',
    municipios: [
      'Moca',
      'Cayetano Germosén',
      'Gaspar Hernández',
      'Jamao al Norte',
    ],
  },
  {
    id: 10,
    nombre: 'Hato Mayor',
    municipios: ['Hato Mayor del Rey', 'El Valle', 'Sabana de la Mar'],
  },
  {
    id: 11,
    municipios: ['m ', '', ' nul'],
    nombre: 'Distrito Nacional',
  },
  {
    id: 12,
    nombre: 'Hermanas Mirabal',
    municipios: ['Salcedo ', 'Tenares', 'Villa Tapia'],
  },
  {
    id: 13,
    nombre: 'Independencia',
    municipios: [
      'Jimaní',
      'Cristóbal',
      'Duvergé',
      'La Descubierta',
      'Mella',
      'Postrer Río',
    ],
  },
  {
    id: 14,
    nombre: 'La Altagracia',
    municipios: ['Higüey', 'San Rafael del Yuma'],
  },
  {
    id: 15,
    nombre: 'La Romana',
    municipios: ['La Romana', 'Guaymate', 'Villa Hermosa'],
  },
  {
    id: 16,
    nombre: 'La Vega',
    municipios: [
      'La Concepción de La Vega',
      'Constanza ',
      'Jarabacoa',
      'Jima Abajo',
    ],
  },
  {
    id: 17,
    nombre: 'María Trinidad Sánchez',
    municipios: [' Nagua', 'Cabrera', 'El Factor', 'Río San Juan'],
  },
  {
    id: 18,
    nombre: 'Monseñor Nouel',
    municipios: ['Bonao', 'Maimón', 'Piedra Blanca'],
  },
  {
    id: 19,
    nombre: 'Montecristi',
    municipios: [
      'Montecristi',
      'Castañuela',
      'Guayubín',
      'Las Matas de Santa Cruz',
      'Pepillo Salcedo',
      'Villa Vásquez',
    ],
  },
  {
    id: 20,
    nombre: 'Monte Plata',
    municipios: [
      'Monte Plata',
      'Bayaguana',
      'Peralvillo',
      'Sabana Grande de Boyá',
      'Yamasá',
    ],
  },
  {
    id: 21,
    nombre: 'Pedernales',
    municipios: ['Pedernales ', 'Oviedo'],
  },
  {
    id: 22,
    nombre: 'Peravia',
    municipios: ['Baní', 'Nizao'],
  },
  {
    id: 23,
    nombre: 'Puerto Plata',
    municipios: [
      'Puerto Plata ',
      'Altamira',
      'Guananico',
      'Imbert',
      'Luperón',
      'Sosúa',
      'Villa Isabela',
      'Villa Montellano',
    ],
  },
  {
    id: 24,
    nombre: 'Samaná',
    municipios: ['Samaná', 'Las Terrenas', 'Sánchez'],
  },
  {
    id: 25,
    nombre: 'San Cristóbal',
    municipios: [
      'San Cristóbal',
      'Bajos de Haina',
      'Cambita Garabito',
      'Los Cacaos',
      'Sabana Grande de Palenque',
      'San Gregorio de Nigua',
      'Villa Altagracia',
      'Yaguate',
    ],
  },
  {
    id: 26,
    nombre: 'San José de Ocoa',
    municipios: ['San José de Ocoa', 'Rancho Arriba', 'Sabana Larga'],
  },
  {
    id: 27,
    nombre: 'San Juan',
    municipios: [
      'San Juan de la Maguana',
      'Bohechío',
      'El Cercado',
      'Juan de Herrera',
      'Las Matas de Farfán',
      'Vallejuelo',
    ],
  },
  {
    id: 28,
    nombre: 'San Pedro de Macorís',
    municipios: [
      'San Pedro de Macorís',
      'Consuelo',
      'Guayacanes',
      'Quisqueya',
      'Ramón Santana',
      'San José de Los Llanos',
    ],
  },
  {
    id: 29,
    nombre: 'Sánchez Ramírez',
    municipios: ['Cotuí', 'Cevicos', 'Fantino', 'La Mata'],
  },
  {
    id: 30,
    nombre: 'Santiago',
    municipios: [
      'Santiago',
      'Bisonó',
      'Jánico',
      'Licey al Medio',
      'Puñal',
      'Sabana Iglesia',
      'San José de las Matas',
      'Tamboril',
      'Villa González',
    ],
  },
  {
    id: 31,
    nombre: 'Santiago Rodríguez',
    municipios: ['San Ignacio de Sabaneta', 'Los Almácigos', 'Monción'],
  },
  {
    id: 32,
    nombre: 'Santo Domingo',
    municipios: [
      'Santo Domingo Este',
      'Boca Chica',
      'Los Alcarrizos',
      'Pedro Brand',
      'San Antonio de Guerra',
      'Santo Domingo Norte',
      'Santo Domingo Oeste',
    ],
  },
  {
    id: 33,
    nombre: 'Valverde',
    municipios: ['Mao', 'Esperanza', 'Los Alcarrizos', '. Laguna Salada'],
  },
];
